In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv("allPlayerData.csv")
df

,Unnamed: 0,Season,Player,Pos,Age,Tm,G,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Player-additional
0,1,1985-1986,Kareem Abdul-Jabbar*,C,38,LAL,79,2629,22.7,0.603,...,26.6,7.6,3.2,10.8,0.197,4.4,1.0,5.4,4.9,abdulka01
1,2,1985-1986,Alvan Adams,C,31,PHO,78,2005,15.3,0.547,...,19.4,1.2,2.7,3.9,0.094,0.2,1.5,1.6,1.8,adamsal01
2,3,1985-1986,Michael Adams,PG,23,SAC,18,139,8.0,0.406,...,17.5,-0.2,0.1,-0.1,-0.028,-3.6,-0.2,-3.8,-0.1,adamsmi01
3,4,1985-1986,Mark Aguirre,SF,26,DAL,74,2501,19.2,0.547,...,29.0,3.7,0.9,4.7,0.090,2.3,-2.1,0.3,1.4,aguirma01
4,5,1985-1986,Danny Ainge,SG,26,BOS,80,2407,13.6,0.562,...,15.2,3.6,3.2,6.8,0.136,-0.1,1.0,0.9,1.8,aingeda01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20313,20314,2021-2022,Thaddeus Young,PF,33,TOR,26,475,15.8,0.526,...,16.0,0.5,0.8,1.3,0.127,-0.2,2.2,2.0,0.5,youngth01
20314,20315,2021-2022,Trae Young,PG,23,ATL,76,2652,25.4,0.603,...,34.4,9.0,1.0,10.0,0.181,7.1,-2.0,5.2,4.8,youngtr01
20315,20316,2021-2022,Omer Yurtseven,C,23,MIA,56,706,17.4,0.546,...,19.9,0.8,1.4,2.1,0.145,-1.4,0.4,-1.0,0.2,yurtsom01
20316,20317,2021-2022,Cody Zeller,C,29,POR,27,355,17.2,0.627,...,15.9,0.9,0.2,1.1,0.143,-1.2,-1.0,-2.1,0.0,zelleco01
20317,20318,2021-2022,Ivica Zubac,C,24,LAC,76,1852,19.2,0.660,...,16.8,4.3,2.9,7.2,0.187,-0.1,0.8,0.7,1.3,zubaciv01

In [54]:
df['Team'] = df['Tm']
df_sub = df[['Season', 'Player', 'Team']]
df_sort = df_sub.sort_values(by = ['Team', 'Season'])
df_list = pd.DataFrame(df_sort.groupby(['Team', 'Season'])['Player'].apply(list))

In [55]:
df_list

                                                           Player
Team Season
ATL  1985-1986  [John Battle, Antoine Carr, Lorenzo Charles, J...
     1986-1977  [John Battle, Antoine Carr, Scott Hastings, Ce...
     1987-1988  [John Battle, Antoine Carr, Scott Hastings, Jo...
     1988-1989  [John Battle, Dudley Bradley, Antoine Carr, Du...
     1989-1990  [John Battle, Antoine Carr, Duane Ferrell, Jon...
...                                                           ...
WSB  1992-1993  [Mark Acres, Michael Adams, Steve Burtt, Rex C...
     1993-1994  [Michael Adams, Ron Anderson, Manute Bol, Mitc...
     1994-1995  [Mitchell Butler, Rex Chapman, Calbert Cheaney...
     1995-1996  [Mitchell Butler, Calbert Cheaney, Michael Cur...
     1996-1997  [Ashraf Amaya, Calbert Cheaney, Matt Fish, Har...

[1094 rows x 1 columns]