In [1]:
import pandas as pd
import numpy as np

Data gathered from https://www.basketball-reference.com/leagues/NBA_stats_per_game.html

In [2]:
raw_df = pd.read_csv('./raw/LeagueAverages.csv', skiprows=1)
raw_df.head()

,Rk,Season,Lg,Age,Ht,Wt,G,MP,FG,FGA,...,PTS,FG%,3P%,FT%,Pace,eFG%,TOV%,ORB%,FT/FGA,ORtg
0,1,2022-23,NBA,26.2,6-7,217.0,325,242.0,41.3,88.1,...,113.0,0.469,0.356,0.782,99.3,0.538,13.1,24.2,0.207,112.8
1,2,2021-22,NBA,26.1,6-6,215.0,1230,241.4,40.6,88.1,...,110.6,0.461,0.354,0.775,98.2,0.532,12.3,23.2,0.192,112.0
2,3,2020-21,NBA,26.1,6-6,217.0,1080,241.4,41.2,88.4,...,112.1,0.466,0.367,0.778,99.2,0.538,12.4,22.2,0.192,112.3
3,4,2019-20,NBA,26.1,6-6,218.0,1059,241.8,40.9,88.8,...,111.8,0.460,0.358,0.773,100.3,0.529,12.8,22.5,0.201,110.6
4,5,2018-19,NBA,26.3,6-6,219.0,1230,241.6,41.1,89.2,...,111.2,0.461,0.355,0.766,100.0,0.524,12.4,22.9,0.198,110.4

In [32]:
df = raw_df.drop(columns = ['Rk', 'Lg'])
for i in range(df.shape[0]):
    df["Season"].values[i] = df["Season"].iloc[i].split("-")[0][:2] + df["Season"].iloc[i].split("-")[1]
#     df["Ht"].values[i] = int(df["Ht"].iloc[i].split("-")[0]) + df["Season"].iloc[i].split("-")[1]
df["Season"] = pd.to_numeric(df["Season"])
df.loc[df['Season'] == 1900, 'Season'] = 2000

In [35]:
df[df['Season']>=1985].to_csv('./modified/cleaned_LeagueAverages.csv', index=False)

## Player Averages
---
DATA collected form STATMUSE:
https://www.statmuse.com/nba/ask?q=nba+league+average+ppg+per+position+per+season+1984-85+to+2021-22

In [17]:
raw_df = pd.read_table('./raw/player_LeagueAverages.txt')

In [14]:
raw_df.head()

,POSITION,SEASON,GP,PPG,PER,MPG,RPG,APG,SPG,BPG,...,FT%,MIN,PTS,REB,AST,STL,BLK,TOV,PF,+/-
0,Point Guard,1984-85,3463.0,10.1,14.9,25.1,2.4,5.4,1.3,0.2,...,79.1,"87,090","34,962","8,181","18,647","4,553",542,"6,750","7,374",NaN
1,Shooting Guard,1984-85,3908.0,11.9,15.1,23.7,2.6,3.0,1.0,0.2,...,79.9,"92,711","46,367","10,256","11,749","3,842",911,"6,719","8,472",NaN
2,Small Forward,1984-85,3773.0,12.8,16.0,24.0,4.1,2.1,0.8,0.4,...,77.5,"90,494","48,476","15,580","7,929","3,034","1,378","6,330","8,592",NaN
3,Power Forward,1984-85,4241.0,9.9,14.2,22.8,5.7,1.5,0.6,0.7,...,72.9,"96,750","42,066","24,073","6,169","2,689","2,811","7,222","11,815",NaN
4,Center,1984-85,3904.0,9.5,14.8,22.6,6.1,1.3,0.5,1.1,...,73.9,"88,295","37,170","23,918","5,021","2,004","4,377","6,206","10,783",NaN

In [9]:
raw_df.columns

Index(['POSITION', 'SEASON', 'GP', 'PPG', 'PER', 'MPG', 'RPG', 'APG', 'SPG',
       'BPG', 'TPG', 'FGM', 'FGA', 'FG%', '3PM', '3PA', '3P%', 'FTM', 'FTA',
       'FT%', 'MIN', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', '+/-'],
      dtype='object')

In [23]:
raw_df.tail(n=10)

,POSITION,SEASON,GP,PPG,PER,MPG,RPG,APG,SPG,BPG,...,FT%,MIN,PTS,REB,AST,STL,BLK,TOV,PF,+/-
181,Shooting Guard,2020-21,6213.0,10.6,13.2,22.7,3.0,2.2,0.7,0.3,...,81.1,"140,932","65,551","18,720","13,574","4,514","1,820","7,192","10,539",-545.0
182,Small Forward,2020-21,3597.0,9.9,13.4,23.2,3.9,1.9,0.7,0.4,...,78.9,"83,316","35,744","13,885","6,914","2,613","1,364","3,966","6,374",-1027.0
183,Power Forward,2020-21,5183.0,10.1,15.4,21.9,4.8,1.8,0.6,0.5,...,76.0,"113,471","52,341","24,773","9,109","3,249","2,828","5,663","9,561",1703.0
184,Center,2020-21,3563.0,10.0,18.5,21.9,6.8,1.6,0.6,1.0,...,71.4,"77,938","35,766","24,240","5,775","2,085","3,462","4,419","7,853",-861.0
185,2021-22,36,8.9,9.9,21.3,2.7,2.8,0.8,0.4,1.7,...,768.0,322,97,101,29,13,60,68,-255,NaN
186,Point Guard,2021-22,4981.0,11.4,14.9,24.5,3.3,4.2,0.9,0.3,...,81.0,"121,927","57,030","16,191","20,830","4,643","1,312","8,179","8,730",1110.0
187,Shooting Guard,2021-22,6986.0,10.9,13.3,23.5,3.1,2.3,0.7,0.3,...,81.2,"164,234","76,024","21,438","15,956","5,104","1,903","8,237","11,899",-3168.0
188,Small Forward,2021-22,5100.0,10.2,13.9,23.1,3.9,1.9,0.7,0.4,...,78.8,"117,842","52,232","20,064","9,581","3,751","1,928","5,497","8,946",1553.0
189,Power Forward,2021-22,4815.0,9.4,15.5,21.2,5.0,1.6,0.6,0.6,...,73.8,"102,095","45,501","24,035","7,578","2,835","2,704","4,983","9,434",-1017.0
190,Center,2021-22,4121.0,10.0,19.2,21.1,6.7,1.6,0.6,0.9,...,71.4,"86,871","41,006","27,522","6,590","2,410","3,734","5,161","9,229",1777.0

In [21]:
raw_df[raw_df['SEASON'] =='36']

,POSITION,SEASON,GP,PPG,PER,MPG,RPG,APG,SPG,BPG,...,FT%,MIN,PTS,REB,AST,STL,BLK,TOV,PF,+/-
185,2021-22,36,8.9,9.9,21.3,2.7,2.8,0.8,0.4,1.7,...,768.0,322,97,101,29,13,60,68,-255,NaN

erroneous row from statmuse, will drop.

In [25]:
raw_df = raw_df.drop(index = [185])

In [26]:
raw_df['SEASON'].unique()

array(['1984-85', '1985-86', '1986-87', '1987-88', '1988-89', '1989-90',
       '1990-91', '1991-92', '1992-93', '1993-94', '1994-95', '1995-96',
       '1996-97', '1997-98', '1998-99', '1999-00', '2000-01', '2001-02',
       '2002-03', '2003-04', '2004-05', '2005-06', '2006-07', '2007-08',
       '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14',
       '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20',
       '2020-21', '2021-22'], dtype=object)

In [27]:
df = raw_df.drop(columns = ['+/-'])
for i in range(df.shape[0]):
    df["SEASON"].values[i] = df["SEASON"].iloc[i].split("-")[0][:2] + df["SEASON"].iloc[i].split("-")[1]
#     df["Ht"].values[i] = int(df["Ht"].iloc[i].split("-")[0]) + df["Season"].iloc[i].split("-")[1]
df["SEASON"] = pd.to_numeric(df["SEASON"])
df.loc[df['SEASON'] == 1900, 'SEASON'] = 2000

In [29]:
df.to_csv('./modified/cleaned_player_LeagueAverages.csv', index=False)